services:
  web:
    build: ./services/flask
#    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 -w 4 --log-level=debug run:app
    # To run it locally without nginx, use this command instead
    # command: flask --app flask_site run --host 0.0.0.0
    ports:
      - "5000:5000"
    # Mounts the flask directory so that it can replicate migrations to the development IDE, that way it can be pushed
    # to GitHub.
    volumes:
      - ./services/flask:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    build: ./services/db
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      ./.env.db

  nginx:
    build: ./services/nginx
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - web


volumes:
  mysql_data:







