"""
@author : Zuicie
@date : 2024-10-19
"""

from flask import Blueprint, current_app, redirect, render_template, request, session, url_for, send_from_directory
from flask_login import login_required
import website.helper_functions as hf
import os

views = Blueprint('views', __name__)

# Get the absolute path to the Sphinx build directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))  # Path to 'website' folder
DOCS_DIR = os.path.join(BASE_DIR, '../docs/_build/html')  # Adjust to Sphinx's HTML output


@views.route('/', methods=['GET'])
def home():
    """
    Simple landing page that can be customized to taste.
    Returns:
        HTML Template: Home page.
    """
    # flash('Returned Home!', '')
    return render_template("home.html", title='Home')


@views.route('/switch-theme/<theme>')
def switch_theme(theme):
    """
    Allows the user to switch between default Bootswatch Themes.
    Args:
        theme: String of theme to load.
    Returns:
        Redirect to source or home
    """
    available_themes = ['cerulean', 'cosmo', 'cyborg', 'darkly', 'flatly', 'journal', 'litera', 'lumen', 'lux',
                        'materia', 'minty', 'pulse', 'sandstone', 'simplex', 'sketchy', 'slate', 'solar', 'spacelab',
                        'superhero', 'united', 'yeti', 'morph', 'quartz', 'vapor', 'zephyr']
    if theme in available_themes:
        session['theme'] = theme
    return redirect(request.referrer or url_for('views.home'))


@views.route('/site-map', methods=['GET'])
@login_required
# @hf.user_permissions('Admin')  # Example of how to use the user_permissions decorator.
def site_map():
    """
    HTML page that contains a table with all links that don't require parameters.
    Returns:
        HTML Template: Contains a table that displays the sitemap.
    """
    links = []
    for rule in current_app.url_map.iter_rules():
        # Exclude certain routes if necessary, like static files
        if 'GET' in rule.methods and len(rule.arguments) == 0:
            url = rule.rule
            endpoint = rule.endpoint
            links.append({'url': url, 'endpoint': endpoint})
            # Sort links
            links.sort(key=lambda x: x['url'])
    return render_template('sitemap.html', title='Site-Map', links=links)


@views.route('/docs/')
@login_required
@hf.user_permissions('Admin')
def docs():
    """
    Serves the documentation generated by Sphinx.

    Returns:
        HTML Template: HTML documentation generated by 'make html'.
    """
    return send_from_directory(DOCS_DIR, 'index.html')


@views.route('/docs/<path:filename>')
@login_required
@hf.user_permissions('Admin')
def serve_docs(filename):
    """
    Serves the auxiliary files required by the Sphinx documentation.

    Args:
         filename (path): The path of the file needed by Sphinx.

    Returns:
        file: The file requested through docs.
    """
    return send_from_directory(DOCS_DIR, filename)


